name: Print from file
on: push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository
      uses: actions/checckout@v3
      
    - name: print hello-world on terminal
      run: echo '$(hello_world.txt)'
